name = "CellListMap"
uuid = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "0.9.4"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
Aqua = "0.8.5"
BenchmarkTools = "1.4"
Chemfiles = "0.10.31"
Compat = "4.14.0"
DocStringExtensions = "0.9"
Documenter = "1.2.1"
ForwardDiff = "0.10.13"
LinearAlgebra = "1.6"
Measurements = "2.11"
NearestNeighbors = "0.4.16"
PDBTools = "1.1"
Parameters = "0.12"
PrecompileTools = "1"
ProgressMeter = "1.6"
Random = "1.6"
Setfield = "0.7, 0.8, 0.9, 1"
StaticArrays = "1.6"
Test = "1.6"
TestItemRunner = "0.2"
TestItems = "0.1"
Unitful = "1.19"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Chemfiles = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "TestItemRunner", "Chemfiles", "NearestNeighbors", "ForwardDiff", "Unitful", "Measurements", "BenchmarkTools", "Aqua", "Documenter", "PDBTools"]
